micronaut:
    application:
        name: veganscan-admin-api
    security:
        enabled: true
        user: $API_USER
        password: $API_PASSWORD

mongodb:
    uri: mongodb://$DATABASE_USER:$DATABASE_PASSWORD@ds239157.mlab.com:39157

vegandb:
    database:
        name: heroku_tmp5jg88
