micronaut:
    application:
        name: veganscan-admin-api
    security:
        enabled: true
        user: $API_USER
        password: $API_PASSWORD

mongodb:
    uri: mongodb://$DATABASE_USER:$DATABASE_PASSWORD@ds139167.mlab.com:39167

vegandb:
    database:
        name: heroku_sfl14q82
