micronaut:
    application:
        name: veganscan-admin-api
    server:
        port: 8086
    security:
        enabled: true
        user: user
        password: password

mongodb:
    uri: mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}

vegandb:
    database:
        name: vegandb
