micronaut:
    application:
        name: veganscan
    server:
        port: 8086

mongodb:
    uri: mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}

vegandb:
    database:
        name: vegandb
